
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""  # Leave empty to use the SLAM map
    frame_id: "map"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.25
      lookahead_dist: 0.6
      max_angular_vel: 1.0
      use_velocity_scaled_lookahead_dist: true
      transform_tolerance: 0.2

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names: ["nav2_behavior_tree_nodes"]

waypoint_follower:
  ros__parameters:
    use_sim_time: true

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 10.0
    resolution: 0.05
    rolling_window: true
    width: 3.0
    height: 3.0
    plugins: ["voxel_layer"]
    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: true
      origin_z: 0.0
      z_resolution: 0.05
      z_voxels: 16
      max_obstacle_height: 2.0
      mark_threshold: 0
      observation_sources: "scan"
      scan:
        topic: "scan"
        max_obstacle_height: 2.0
        clearing: true
        marking: true

global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 10.0
    resolution: 0.05
    rolling_window: false
    width: 10.0
    height: 10.0
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"